### ISSUE TITLE
Hide comments?

### ISSUE THREAD

**Issue by coderthetyler** [ulyngs/no-distractions-for-youtube#1]
With the recommendations gone, I find myself mindlessly scrolling down the page and scanning through the comments. Sometimes this is desirable, but I would love to have an option to hide them by default.

By the way, great little extension! I find I am much less tempted to tumble down a YouTube rabbit hole without those pesky recommendations. Well worth the price.

**Comment by ulyngs** [comment]
I think this is a great suggestion. I'll think about how to implement it in the next update!

Also, thanks for the kind words - it'd be really helpful if you would consider putting those in a review on the App Store! :)

**Comment by ulyngs** [comment]
This has been implemented
