### ISSUE TITLE
Hiding recommended videos - hides the Playlist as well???

### ISSUE THREAD

**Issue by martintomoya** [ulyngs/no-distractions-for-youtube#2]
Just purchased the app and it does remove the recommended videos however it also removes the playlist if you happen to be playing multiple videos ? Can this be fixed? thanks!

**Comment by ulyngs** [comment]
Thanks for flagging this - I've been thinking about this too. I agree that when you're watching a playlist of videos, those videos should not be removed.

I'll try and fix this and update the app before the end of next week! :)

**Comment by ulyngs** [comment]
I have fixed this and submitted and updated version to the App Store - should be out in a couple of days.

**Comment by martintomoya** [comment]
Thanks so much for such a quick fix! Looking forward to updating the app once in app store. Keep up the good work @ulyngs !

**Comment by ulyngs** [comment]
Update should now be available on the App Store! :)
