### ISSUE TITLE
Can't find it in Safari Extensions Preferences

### ISSUE THREAD

**Issue by LoneFireBlossom** [ulyngs/no-distractions-for-youtube#3]
MacBook Pro (16-inch, 2019)
Catalina 10.15.7
Safari Version 15.2 (15612.3.5.10.1, 15612)

I have bought and used this extensions for several weeks, and it worked well.
But today I find it "disappears" in Safari Extensions Preferences and I don't know why. I don't know when this issue happened.
(It should be on the top of the window)
<img width="780" alt="image" src="https://user-images.githubusercontent.com/50087596/146000426-9f2c6ba7-2d98-4b27-b61c-c00cd751134e.png">

I bought this extension from App Store of China Mainland, and now I can't find this extension in the App Store. 
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/50087596/145999689-860d9c5a-bad3-4472-9920-d267c44170c6.png">

(I remember that if Apple remove a app in App Store, it will send a letter to the developer.)
I want to ask that is this extension removed from the China Mainland App Store?
Is there any connection between "can't find it in App Store" and "it disappears in Safari Extensions Preferences"?

**Comment by ulyngs** [comment]
Thanks for flagging this!

The app is temporarily down from the App Store - it's a long story, but it will be back up soon! (Basically, I have rebuilt it to be compatible with iOS and originally submitted the new app under a new name; however I'm trying to make the new version replace the old version and am having some mysterious trouble with the App Store!!)

It should be up in a week at most, I hope - bear with me! :)

**Comment by LoneFireBlossom** [comment]
Thank you for your reply.

I opened youtube.com and found recommended videos back.
So I opened the Safari Extensions Preferences but I could't find it.
(Also vanished in this window)
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/50087596/146004388-77fc9e03-f537-4aa6-b7dd-6f2c32ec17c3.png">

Then I tried to uninstall the extension, and reinstall it from the App Store "history download".
But I still can't find it in Safari Extensions Preferences.

**Comment by ulyngs** [comment]
I have been in communication with the App Store staff and I discovered the issue.

It should be back up within the next 24 hours, thank you so much for your patience!!

**Comment by ulyngs** [comment]
It's back up for me now - do you see it? :)

**Comment by LoneFireBlossom** [comment]
Yes, it returned in App Store.
<img width="738" alt="image" src="https://user-images.githubusercontent.com/50087596/146099938-ff9bca58-23ca-4a99-98c0-27dce86a359e.png">

But I still can't find it in Safari ( I uninstalled and reinstalled it again. Then I quited and reopened Safari.)

**Comment by ulyngs** [comment]
That's bizarre! Any chance you know anyone else in China who use this extension, and can check if they have the same problem? Trying to locate where the issue is.

**Comment by LoneFireBlossom** [comment]
This solution https://github.com/bitwarden/browser/issues/1718#issuecomment-874120202 helped me. I runned the command and restarted my mac, and then the extension revealed.
